/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp3_cote_francis_stlaurent_daren;
import java.sql.*;
import java.awt.*;
import javax.swing.*;

import javax.swing.JFrame;

/**
 *
 * @author 201106779
 */
public class GestionDisqueForm extends javax.swing.JFrame {

    /**
     * Creates new form GestionDisqueForm
     */
    public JFrame callBackForm = null;
    public GestionDisqueForm(ConnectionOracle conn) {
        initComponents();
        this.connBD = conn;
        // appel du bouton premier
        BTN_Premier.doClick();
        listerGenre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TB_NumDisque = new javax.swing.JTextField();
        TB_Titre = new javax.swing.JTextField();
        TB_Prix = new javax.swing.JTextField();
        TB_Annee = new javax.swing.JTextField();
        TB_Langue = new javax.swing.JTextField();
        TB_Nbchanson = new javax.swing.JTextField();
        BTN_Premier = new javax.swing.JButton();
        BTN_Precedent = new javax.swing.JButton();
        BTN_Suivant = new javax.swing.JButton();
        BTN_Dernier = new javax.swing.JButton();
        BTN_Ajouter = new javax.swing.JButton();
        BTN_Modifier = new javax.swing.JButton();
        BTN_Supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Liste_Artiste = new javax.swing.JList();
        BTN_ListerArtiste = new javax.swing.JToggleButton();
        CB_Genre = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Ok.setText("Ok");
        BTN_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_OkActionPerformed(evt);
            }
        });

        jLabel2.setText("# de disque");

        jLabel4.setText("Genre");

        jLabel5.setText("Année de sortie");

        jLabel6.setText("Langue");

        jLabel7.setText("Nb de chansons");

        jLabel9.setText("Titre");

        jLabel10.setText("Prix");

        TB_NumDisque.setEnabled(false);

        BTN_Premier.setText("<<");
        BTN_Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PremierActionPerformed(evt);
            }
        });

        BTN_Precedent.setText("Précedent");
        BTN_Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecedentActionPerformed(evt);
            }
        });

        BTN_Suivant.setText("Suivant");
        BTN_Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SuivantActionPerformed(evt);
            }
        });

        BTN_Dernier.setText(">>");
        BTN_Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DernierActionPerformed(evt);
            }
        });

        BTN_Ajouter.setText("Ajouter");
        BTN_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterActionPerformed(evt);
            }
        });

        BTN_Modifier.setText("Modifier");
        BTN_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModifierActionPerformed(evt);
            }
        });

        BTN_Supprimer.setText("Supprimer");
        BTN_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SupprimerActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Liste_Artiste);

        BTN_ListerArtiste.setText("Lister Artistes / disque");
        BTN_ListerArtiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ListerArtisteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(78, 78, 78)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TB_Prix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TB_Titre, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(TB_NumDisque))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTN_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BTN_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(BTN_Ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_ListerArtiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TB_Langue, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(TB_Annee, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(CB_Genre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(TB_Nbchanson, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BTN_Premier)
                                    .addGap(18, 18, 18)
                                    .addComponent(BTN_Precedent)
                                    .addGap(18, 18, 18)
                                    .addComponent(BTN_Suivant)
                                    .addGap(18, 18, 18)
                                    .addComponent(BTN_Dernier))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TB_NumDisque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(BTN_Ajouter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TB_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_Prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Supprimer)
                    .addComponent(jLabel4)
                    .addComponent(CB_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TB_Annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TB_Langue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TB_Nbchanson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Premier)
                    .addComponent(BTN_Precedent)
                    .addComponent(BTN_Suivant)
                    .addComponent(BTN_Dernier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(BTN_Ok)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_ListerArtiste)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void listerGenre()
    {
        String sqlGenre = "select numgenre,nomgenre from Genres";
        try
        {
            Statement stmGenre = connBD.getConnection().createStatement();
            ResultSet rstGenre = stmGenre.executeQuery(sqlGenre);
            while(rstGenre.next())
            {
                CB_Genre.addItem(rstGenre.getString(1)+" "+rstGenre.getString(2));
            }
        }
        catch(SQLException sqlex){ System.out.println(sqlex);}
    }
    private void BTN_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_OkActionPerformed
        // TODO add your handling code here:
         new JFrameGestion(connBD).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BTN_OkActionPerformed

    private void BTN_PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PremierActionPerformed
        // TODO add your handling code here:
        try 
     {
         Statement stm1 = connBD.getConnection().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
         rst = stm1.executeQuery(sql1);
         if (rst.first())
         {
            TB_NumDisque.setText (((Integer)rst.getInt(1)).toString());
            TB_Titre.setText(rst.getString(2));
            TB_Prix.setText(((Integer)rst.getInt(3)).toString());
            CB_Genre.setSelectedItem(rst.getString(4));
            TB_Annee.setText(((Integer)rst.getInt(5)).toString());
            TB_Langue.setText(rst.getString(6));
            TB_Nbchanson.setText (((Integer)rst.getInt(7)).toString());
            
         
         }
     }
     catch(SQLException se)
     { 
         System.out.println(se);
     }
    }//GEN-LAST:event_BTN_PremierActionPerformed

    private void BTN_PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecedentActionPerformed
        // TODO add your handling code here:
        try 
       {
          if (rst.first())
         {
            TB_NumDisque.setText (((Integer)rst.getInt(1)).toString());
            TB_Titre.setText(rst.getString(2));
            TB_Prix.setText(((Integer)rst.getInt(3)).toString());
            CB_Genre.setSelectedItem(rst.getString(4));
            TB_Annee.setText(((Integer)rst.getInt(5)).toString());
            TB_Langue.setText(rst.getString(6));
            TB_Nbchanson.setText (((Integer)rst.getInt(7)).toString());
            
         
         }
          else 
          {
            JOptionPane.showMessageDialog(this, "Précedent impossible");
          }
       
       }
   
     catch(SQLException se)
     {
        JOptionPane.showMessageDialog(this, "précedent impossible");
     }
    }//GEN-LAST:event_BTN_PrecedentActionPerformed

    private void BTN_SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SuivantActionPerformed
        // TODO add your handling code here:
         try 
     {
         if(rst.next())
          {
            TB_NumDisque.setText (((Integer)rst.getInt(1)).toString());
            TB_Titre.setText(rst.getString(2));
            TB_Prix.setText(((Integer)rst.getInt(3)).toString());
            CB_Genre.setSelectedItem(rst.getString(4));
            TB_Annee.setText(((Integer)rst.getInt(5)).toString());
            TB_Langue.setText(rst.getString(6));
            TB_Nbchanson.setText (((Integer)rst.getInt(7)).toString());
          }
      
         else 
          {
            JOptionPane.showMessageDialog(this, "suivant impossible");
          }
     }
     
     catch(SQLException se)
     {
        JOptionPane.showMessageDialog(this, "Suivant imposible");
     
     }
    }//GEN-LAST:event_BTN_SuivantActionPerformed

    private void BTN_DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DernierActionPerformed
        // TODO add your handling code here:
      try 
      {
         if(rst.last())
         {
            TB_NumDisque.setText (((Integer)rst.getInt(1)).toString());
            TB_Titre.setText(rst.getString(2));
            TB_Prix.setText(((Integer)rst.getInt(3)).toString());
            CB_Genre.setSelectedItem(rst.getString(4));
            TB_Annee.setText(((Integer)rst.getInt(5)).toString());
            TB_Langue.setText(rst.getString(6));
            TB_Nbchanson.setText (((Integer)rst.getInt(7)).toString());
         }

      
     }
     
     catch(SQLException se){
        JOptionPane.showMessageDialog(this, "dernier imposible");
     
     }
    }//GEN-LAST:event_BTN_DernierActionPerformed

    private void BTN_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterActionPerformed
        // TODO add your handling code here:
        new AjoutDisqueForm(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_AjouterActionPerformed

    private void BTN_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModifierActionPerformed
        // TODO add your handling code here:
      String sqlupdate ="update Disques set titredisque = ? , prix = ? , numgenre = ?,anneedisque = ?,langue = ?, nbchansons = ? where numerodisque = " + TB_NumDisque.getText();
      
      String titre= TB_Titre.getText();
      int prix = Integer.parseInt(TB_Prix.getText());
      int genre =Integer.parseInt(CB_Genre.getSelectedItem().toString().substring(0, 1));
      int annee = Integer.parseInt(TB_Annee.getText());
      String langue = TB_Langue.getText();
      int nbchansons = Integer.parseInt(TB_Nbchanson.getText());

      try
         {
            PreparedStatement stmajout= connBD.getConnection().prepareStatement(sqlupdate);
            stmajout.setString(1,titre);
            stmajout.setInt(2,prix);
            stmajout.setInt(3,genre);
            stmajout.setInt(4, annee);
            stmajout.setString(5, langue);
            stmajout.setInt(6, nbchansons);
            stmajout.executeUpdate();
         }

      catch(SQLException se){System.out.println("err" + se);}
    }//GEN-LAST:event_BTN_ModifierActionPerformed

    private void BTN_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SupprimerActionPerformed
        String sqlDelete = "DELETE FROM Disques WHERE NUMERODISQUE = "+TB_NumDisque.getText();
        
        try
        {
            Statement stmDelete = connBD.getConnection().createStatement();
            stmDelete.executeQuery(sqlDelete);
        }
        catch(SQLException se)
        {
            System.out.println("err" + se);
        }
    }//GEN-LAST:event_BTN_SupprimerActionPerformed

    private void BTN_ListerArtisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ListerArtisteActionPerformed
        String sql2 = "Select A.prenomArtiste,A.nomArtiste from Artistes A inner join ArtisteDisques AD on A.NumeroArtiste = AD.NumeroArtiste inner join Disques D on AD.NumeroDisque = D.NumeroDisque where D.NumeroDisque = ? ";
        try
        {
            PreparedStatement stm3 = connBD.getConnection().prepareStatement(sql2);
            String numDisque = TB_NumDisque.getText();
            stm3.setString(1,numDisque);
            ResultSet rst3 = stm3.executeQuery();
            DefaultListModel listModel = new DefaultListModel();
            while(rst3.next())
            {
                listModel.addElement(rst3.getString(1)+ " "+ rst3.getString(2));
            }
            Liste_Artiste.setModel(listModel);
        }
        catch(SQLException sqlex){ System.out.println(sqlex);}
    }//GEN-LAST:event_BTN_ListerArtisteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDisqueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDisqueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDisqueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDisqueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new GestionDisqueForm().setVisible(true);
            }
        });
    }
   // Declartion des autres variables.  
   ConnectionOracle connBD;
   ResultSet rst ;
   String sql1 = "Select D.numerodisque,D.titredisque,D.prix,G.nomgenre,D.anneedisque,D.langue,D.nbchansons from disques D inner join Genres G on D.NumGenre = G.Numgenre";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Ajouter;
    private javax.swing.JButton BTN_Dernier;
    private javax.swing.JToggleButton BTN_ListerArtiste;
    private javax.swing.JButton BTN_Modifier;
    private javax.swing.JButton BTN_Ok;
    private javax.swing.JButton BTN_Precedent;
    private javax.swing.JButton BTN_Premier;
    private javax.swing.JButton BTN_Suivant;
    private javax.swing.JButton BTN_Supprimer;
    private javax.swing.JComboBox CB_Genre;
    private javax.swing.JList Liste_Artiste;
    private javax.swing.JTextField TB_Annee;
    private javax.swing.JTextField TB_Langue;
    private javax.swing.JTextField TB_Nbchanson;
    private javax.swing.JTextField TB_NumDisque;
    private javax.swing.JTextField TB_Prix;
    private javax.swing.JTextField TB_Titre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
